services:
  app:
    image: node:22.12.0-alpine3.21
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_HOST=mysql
      - DB_HOST = 172.18.0.1
      - DB_PORT = 3306
      - DB_NAME = mydb
      - DB_USER = ovatsug
      - DB_PASSWORD = vatsugao
      - NEXT_URL = http://localhost:3000
    ports:
      - "3000:3000"
    command: ["tail", "-f" ,"/dev/null"]
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: ovatsug
      MYSQL_PASSWORD: vatsugao
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:  
  mysql_data: